# This cookbook configuration is used to configure the tasks required 
# to maintain the simplicialStructures paper.
#

paper:
  name: simplicialStructures
  version: 0.0.1

texStyle:
  name: simplicialStructures
  version: 0.0.1
  files: []
