#!/bin/bash

# This bash shell determines which base application to use:
#  racket if the first argument is check
#  ruby otherwise

diSimpDir=$HOME/.diSimp
diSimpRuby=$diSimpDir/ruby/lib
diSimpRacket=$diSimpDir/racket/pkgs

if [ 0 -lt $# ]; then 
  if [ $1 = 'check' ]; then
    if [ -r $diSimpRacket/diSimp-check ]; then
      #
      # Fire up racket with the diSimp main
      #
      shift # remove first "check" parameter
      exec $diSimpRacket/diSimp-check $*
    fi
  fi
fi

# Fire up ruby ....
exec $diSimpRuby/diSimp $*
