#!/bin/bash

# This bash shell determines which base application to use:
#  racket if the first argument is check
#  ruby otherwise

diSimpLib=$HOME/.diSimp/lib

if [ 0 -lt $# ]; then 
  if [ $1 = 'check' ]; then
    if [ -r $diSimpLib/main.rkt ]; then
      #
      # Fire up racket with the diSimp main
      #
      exec racket --script $diSimpLib/main.rkt --curDir $PWD $*
    fi
  fi
fi

# Fire up ruby ....
exec ruby $diSimpLib/main.rb $PWD $*
