#!/bin/bash

# This bash script simply copies the diSimp script to the user's local
# bin directory.

# Change the following shell variable to reflect the location you want
# to use for the diSimp build command
#
BINDIR=$HOME/bin

# Change the following shell variable to reflect the location you want
# to use for the diSimp libraries and global configuration
#
GLOBALDIR=$HOME/.diSimp

RUBYLIB=$GLOBALDIR/ruby/lib

cp diSimp $BINDIR
mkdir -p $RUBYLIB
mkdir -p $RUBYLIB/diSimpBuilder
mkdir -p $RUBYLIB/diSimpBuilder/commands
mkdir -p $RUBYLIB/diSimpBuilder/templates
cp -R lib/* $RUBYLIB

# Now we need to ensure all of the required gems are installed....
echo "We will need your sudo password to install the required gems"
sudo gem install mercenary
